name: movies-site
recipe: drupal10
config:
  webroot: web

services:
  myservice:
    type: phpmyadmin

build:
  run:
    - composer install
    - drush site-install --db-url=mysql://drupal10:drupal10@database/drupal10 --account-pass=admin -y
  

