name: movies-site
recipe: drupal10
config:
  webroot: web

services:
  myservice:
    type: phpmyadmin

  appserver:
    build_as_root:
      - composer install
    build:
      - drush site-install --db-url=mysql://drupal10:drupal10@database/drupal10 --account-pass=admin -y
  
  database:
    portforward: true


